// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:WarQuest.WinFormMVC.Models.UnitCollection._unitCollection")]
[assembly: SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'new frmBoard()' before all references to it are out of scope.", Justification = "<Pending>", Scope = "member", Target = "~M:WarQuest.WinFormMVC.MainForm.butStart_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Build", "CA1303:Method 'string MainForm.DisplayIntoListTheChosenUnits(ListBox mylstBxUnits)' passes a literal string as parameter 'message' of a call to 'Exception.Exception(string? message)'. Retrieve the following string(s) from a resource table instead: \"Impossible case\".", Justification = "<Pending>", Scope = "member", Target = "~M:WarQuest.WinFormMVC.MainForm.DisplayIntoListTheChosenUnits(System.Windows.Forms.ListBox)~System.String")]
[assembly: SuppressMessage("Build", "CA1307:The behavior of 'string.Replace(string, string?)' could vary based on the current user's locale settings. Replace this call in 'WarQuest.WinFormMVC.MainForm.menuStripMain_ItemClicked(object, System.Windows.Forms.ToolStripItemClickedEventArgs)' with a call to 'string.Replace(string, string?, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:WarQuest.WinFormMVC.MainForm.menuStripMain_ItemClicked(System.Object,System.Windows.Forms.ToolStripItemClickedEventArgs)")]
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'int SameUnitCollection.AddSameUnit(Unit unit)', validate parameter 'unit' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:WarQuest.WinFormMVC.Models.SameUnitCollection.AddSameUnit(WarQuest.WinFormMVC.Models.Unit)~System.Int32")]
[assembly: SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'new MainForm()' before all references to it are out of scope.", Justification = "<Pending>", Scope = "member", Target = "~M:WarQuest.WinFormMVC.Program.Main")]
[assembly: SuppressMessage("Build", "CA1065:get_BuidingType creates an exception of type NotImplementedException, an exception type that should not be raised in a property. If this exception instance might be raised, use a different exception type, convert this property into a method, or change this property's logic so that it no longer raises an exception.", Justification = "<Pending>", Scope = "member", Target = "~P:WarQuest.WinFormMVC.Models.UnitBuilder.BuidingType")]
[assembly: SuppressMessage("Build", "CA1065:get_DestroyType creates an exception of type NotImplementedException, an exception type that should not be raised in a property. If this exception instance might be raised, use a different exception type, convert this property into a method, or change this property's logic so that it no longer raises an exception.", Justification = "<Pending>", Scope = "member", Target = "~P:WarQuest.WinFormMVC.Models.UnitDestroyer.DestroyType")]
